export const LOGIN_START = 'LOGIN_START';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
export const LOGIN_SUCCCESS = 'LOGIN_SUCCCESS';
export const LOGIN_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_IN_PROGRESS = 'LOGOUT_IN_PROGRESS';
export const LOGOUT_RECEIVED = 'LOGOUT_RECEIVED';

export const SIGNUP_IN_PROGRESS = 'SIGNUP_IN_PROGRESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_START = 'SIGNUP_START';

export const USER_ACTIVATION_INIT = 'USER_ACTIVATION_INIT';
export const USER_ACTIVATION_START = 'USER_ACTIVATION_START';
export const USER_ACTIVATION_SUCCESS = 'USER_ACTIVATION_SUCCESS';
export const USER_ACTIVATION_ERROR = 'USER_ACTIVATION_ERROR';
